# 基准地址
baseURL = 'http://pinggod.com'
# 是否编译草稿
buildDrafts = true
# 默认内容语言
DefaultContentLanguage = 'zh'
# 使用 RobotsTxt
enableRobotsTXT = true
# 谷歌分析用户 ID
googleAnalytics = ''
# 指定编译时忽略的文件
ignoreFiles = ["postcss"]
# 页面语言类型
languageCode = "zh-CN"
# 每页数量
paginate = 3
# 使用的主题名
theme = "dido-hugo"
# 网站标题
title = 'Pinggod'
# 自动检测中日韩（CJK，Chinese / Japanese / Korean）语言
hasCJKLanguage = true
# 详细的编译信息
verbose = true

# 永久链接格式
[permalinks]
     post = '/:year/:title/'

# 顶部导航
[[Menu.top]]
    name = "Blog"
    weight = 1
    url = "/post/"
[[Menu.top]]
    name = "Tag"
    weight = 2
    url = "/tags/"
[[Menu.top]]
    name = "Category"
    weight = 3
    url = "/categories/"
[[Menu.top]]
    name = "RSS"
    weight = 4
    url = "/index..xml"

# 底部导航
[[Menu.bottom]]
    name = "About"
    weight = 1
    url = "/about/"
[[Menu.bottom]]
    name = "Contact"
    weight = 2
    url = "/"
[[Menu.bottom]]
    name = "Project"
    weight = 3
    url = "/"
[[Menu.bottom]]
    name = "Licence"
    weight = 4
    url = "/"

[[Menu.sns]]
    name = "email"
    weight = 1
    url = "mailto://pinggodstudio@gmail.com"
[[Menu.sns]]
    name = "weibo"
    weight = 2
    url = "http://weibo.com/sunchongsheng"
[[Menu.sns]]
    name = "wechat"
    weight = 3
    url = "http://p1.bpimg.com/567571/e9906be310dd3d41.png"
[[Menu.sns]]
    name = "github"
    weight = 4
    url = "https://github.com/pinggod"
# [[Menu.sns]]
#     name = "facebook"
#     weight = 5
#     url = "#"
# [[Menu.sns]]
#     name = "twitter"
#     weight = 6
#     url = "#"

[Author]
    name = "@pinggod"
    job = "Front-End Engineer at Alipay"
    avatar = "https://avatars.githubusercontent.com/u/9530963"
    bio = "蚂蚁金服中间件团队正在招聘前端开发工程师，简历请发 pinggodstudio@gmail.com"

# 其他参数
[Params]

# markdown 编译选项
[blackfriday]
    fractions = false
    hrefTargetBlank = true
    plainIDAnchors = true
    extensions = ['hardLineBreak']
